# Site settings

title: Tierethik & Veganismus
email: tierethik_veganismus@gmx.de
author: Tierethik & Veganismus
avatar: /images/Avatar.png
description: Aufklärung und Zitate über Tierethik
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tierethik-veganismus.de/"
github_username: tierethik-veganismus

# Includes an icon in the footer for each username you enter
footer-links:
    dribbble:
    email: tierethik_veganismus@gmx.de
    facebook:
    flickr:
    github:
    instagram: tierethik_veganismus
    linkedin:
    pinterest:
    rss: rss
    twitter:
    stackoverflow:
    youtube: channel/UCNyUQDRIxXp6rtx9eKWbxiA # channel/<your_long_string> or user/<user-name>
    googleplus: # anything in your profile username that comes after plus.google.com/
    playconsole:

# Build settings

# Set the Sass partials directory, as we're using @imports
sass:
    style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
    - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
    - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
    - jekyll-seo-tag
    - jekyll-paginate

include: ["_pages"]

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
