# Site settings

title: Tierethik & Veganismus
email: tierethik_veganismus@gmx.de
author: Tierethik & Veganismus
avatar: /images/Avatar.png
description: Aufklärung und Zitate über Tierethik

domain: www.tierethik-veganismus.de
url: https://www.tierethik-veganismus.de
baseurl: "" # the subpath of your site, e.g. /blog

# Includes an icon in the footer for each username you enter
footer-links:
    email: tierethik_veganismus@gmx.de
    facebook:
    flickr:
    github:
    instagram: tierethik_veganismus
    linkedin:
    pinterest:
    rss: rss
    twitter:
    stackoverflow:
    youtube: channel/UCNyUQDRIxXp6rtx9eKWbxiA # channel/<your_long_string> or user/<user-name>

# Build settings
theme: minima

# Set the Sass partials directory, as we're using @imports
sass:
    style: :expanded # You might prefer to minify using :compressed

include: ["_pages"]

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - LICENSE
    - README.md
    - CNAME
